name: Build, Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        github_access_token: ${{ secrets.ACTION_TOKEN }}
        build_configuration: production
        base_href: /home-automation/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/home-automation
